version: '3.7'
services:
  jupyterhub:
    build: .
    command:
      - /usr/bin/python3
      - /usr/local/bin/jupyterhub
      - --debug
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8888
    environment:
    - OAUTH_ENDPOINT=https://iam-demo.cloud.cnaf.infn.it
    - OAUTH_CALLBACK_URL=http://docker-dev.cern.ch:8888/hub/oauth_callback
    - OAUTH_GROUPS=group1
    - WITH_GPU=false
    - ADMIN_OAUTH_GROUPS=group2

networks:
  default:
    name: jupyterhub
