version: "3.9"

services:
  cvmfs:
    image: dodasts/cvmfs:latest
    privileged: true
    volumes:
      - type: bind
        source: /cvmfs
        target: /cvmfs
        bind:
          propagation: rshared
    environment:
      - REPO_LIST=

  jupyterhub:
    depends_on:
      - http_proxy
      - collab_proxy
    build: .
    command:
      - /usr/bin/python3
      - /usr/local/bin/jupyterhub
      - --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/dodasts/jupyterhub/cookies:/srv/jupyterhub/cookies
      - /usr/local/share/dodasts/jupyterhub/db:/srv/jupyterhub/db
    environment:
      - OAUTH_ENDPOINT=https://iam-demo.cloud.cnaf.infn.it
      - OAUTH_CALLBACK_URL=https://{{HOST_IP}}:8888/hub/oauth_callback
      - OAUTH_GROUPS=group1
      - WITH_GPU=false
      - ADMIN_OAUTH_GROUPS=group2

  http_proxy:
    image: jupyterhub/configurable-http-proxy
    command:
      - configurable-http-proxy
      - --ip=0.0.0.0
      - --port=8888
      - --api-ip=0.0.0.0
      - --api-port=8001
      - --default-target=http://jupyterhub:8088
      - --error-target=http://jupyterhub:8088/hub/error
      # You can create a certificate example with dodas-x509
      - --ssl-key=/usr/local/share/certs/jupyter/hostcert.key
      - --ssl-cert=/usr/local/share/certs/jupyter/hostcert.pem
    volumes:
      - /usr/local/share/certs/jupyter:/usr/local/share/certs/jupyter
    environment:
      - CONFIGPROXY_AUTH_TOKEN=test_token
    ports:
      - 8888:8888
      - 8001:8001

  collab_proxy:
    depends_on:
      - jupyterlab_collab
    build: collab_proxy
    environment:
      - JUPYTERHUB_BASE_URL=http://jupyterhub:8088
      - JUPYTERHUB_API_URL=http://jupyterhub:8088/hub/api
      - JUPYTERHUB_SERVICE_PREFIX=/services/Collaborative-Jupyter/
      # You can create a token with `openssl rand -hex 32`
      - JUPYTERHUB_API_TOKEN=API_TOKEN_EXAMPLE
      # You can create a token with `openssl rand -hex 32`
      - JUPYTER_TOKEN=TOKEN_EXAMPLE
    ports:
      - 8099:8099

  jupyterlab_collab:
    build: jupyterlab_collab
    volumes:
      # You can create a certificate example with dodas-x509
      - /usr/local/share/certs/jupyter:/usr/local/share/certs/jupyter
      - /usr/local/share/collabspace/:/usr/share/workspace
    environment:
      # You can create a token with `openssl rand -hex 32`
      - JUPYTER_TOKEN=TOKEN_EXAMPLE
    ports:
      - 8889:8888

networks:
  default:
    name: jupyterhub
